[package]
name = "rust_perceptron"
version = "0.1.8"
authors = ["gregoryquick <gregory@quicks.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4"
bytemuck = "1.5"
shaderc = "0.7"
rand = "0.8"
futures = "0.3"
wgpu = "0.7"
