cargo-features = ["edition2021"]
[package]
name = "rust_perceptron"
version = "0.5.12"
authors = ["gregoryquick <gregory@quicks.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
bincode = "1.3"
serde = {version = "1.0", features = ["derive"] }
typetag = "0.1"
byteorder = "1.4"
bytemuck = "1.5"
env_logger = "0.9"
shaderc = "0.7"
rand = "0.8"
futures = "0.3"
wgpu = {version = "0.10", features = ["spirv"]}
